-- liquibase formatted sql

-- changeset lunguion:1720980126834-1
CREATE TABLE dislikes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_dislikes PRIMARY KEY (id)
);

-- changeset lunguion:1720980126834-2
CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

-- changeset lunguion:1720980126834-3
CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    price       DOUBLE PRECISION,
    description VARCHAR(255),
    user_id     BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

-- changeset lunguion:1720980126834-4
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset lunguion:1720980126834-5
ALTER TABLE dislikes
    ADD CONSTRAINT uc_16f81fa5cf64c7cda556601de UNIQUE (user_id, product_id);

-- changeset lunguion:1720980126834-6
ALTER TABLE likes
    ADD CONSTRAINT uc_8b6ece145965f5dab1178fe70 UNIQUE (user_id, product_id);

-- changeset lunguion:1720980126834-7
ALTER TABLE dislikes
    ADD CONSTRAINT FK_DISLIKES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

-- changeset lunguion:1720980126834-8
ALTER TABLE dislikes
    ADD CONSTRAINT FK_DISLIKES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset lunguion:1720980126834-9
ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

-- changeset lunguion:1720980126834-10
ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset lunguion:1720980126834-11
ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset lunguion:1720980126834-12
DROP TABLE product CASCADE;

